name: Check if GitHub Actions works properly

on:
  pull_request:
    paths:
      - src/*
      - .github/*

  push:
    branches:
      - test
      - master

jobs:
  check:
    name: Check action
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Slack Notification
        uses: tferreira/matterfy@releases/v1
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ':robot: *Check action*'
          channel: 'develop'
          url: ${{ secrets.SLACK_WEBHOOK }}
